server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: red-config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1111/eureka
  instance:
    instance-id:  aa
    hostname: localhost       

    
    
    